export { default as Login } from './LoginRegister/Login.js';
export { default as ForgotPassword } from './LoginRegister/ForgotPassword.js';
export { default as Register } from './LoginRegister/Register.js';
export { default as ResetPassword } from './LoginRegister/ResetPassword.js';
export { default as SecurityCode } from './LoginRegister/SecurityCode.js';
export { default as InvesterOpportunities } from './InvestorOpportunities/InvestorOpportunities.js';
export { default as AdminOrders } from './AdminOrders/AdminOrders.js';
export { default as AdminOrderDetails } from './AdminOrderDetails/AdminOrderDetails.js';
export { default as AdminInvestorPortfolio } from './AdminInvestorPortfolio/AdminInvestorPortfolio.js';
export { default as InvesterIndividual } from './InvesterIndividual/InvesterIndividual.js';
export { default as Profile } from './Profile/Profile.js';
export { default as DealInvestmentOpportunity } from './DealInvestmentOpportunity/DealInvestmentOpportunity.js'
export { default as AdminInvestors } from './AdminInvestors/AdminInvestors.js';
export { default as AdminOpportunities } from './AdminOpportunities/AdminOpportunities.js';
export { default as AddOpportunity } from './AddOpportunity/AddOpportunity.js';
export { default as ViewOpportunity } from './ViewOpportunity/ViewOpportunity.js';
export { default as MyHoldings } from './MyHoldings/MyHoldings.js';
export { default as HoldingDetails } from './HoldingDetails/HoldingDetails.js';
export { default as ExpressIntrest } from './ExpressIntrest/ExpressIntrest.js';
export { default as AdminCompanyList } from './AdminCompanyList/AdminCompanyList.js';
export { default as AdminCompanyAddEdit } from './AdminCompanyAddEdit/AdminCompanyAddEdit.js';
export { default as EditProfile } from './EditProfile/EditProfile.js';
export { default as AddJoinInvester } from './AddJoinInvester/AddJoinInvester.js';
export { default as EditEntity } from './EditEntity/EditEntity.js';
export { default as LegelData } from './LegelData/LegelData.js';
export { default as SignupSuccess } from './LoginRegister/SignupSuccess.js';
export { default as PasswordSuccess } from './LoginRegister/PasswordSuccess.js';
export { default as OpportunitySuccess} from './OpportunitySuccess/OpportunitySuccess.js';
export { default as ForgotPasswordSuccess} from './LoginRegister/ForgotPasswordSuccess.js';
export { default as DocumentPermissions} from './DocumentPermissions/DocumentPermissions.js';
export { default as Terms} from './Terms/Terms.js';
export { default as Privacy } from './Privacy/Privacy.js';
